# Generated by Django 2.1b1 on 2019-01-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
                ('no_of_players', models.IntegerField(default=2)),
                ('winner', models.CharField(max_length=50)),
                ('answer', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=200)),
                ('rounds', models.IntegerField(default=200)),
                ('seconds', models.IntegerField(default=3600)),
                ('rounds_over', models.IntegerField(default=0)),
                ('seconds_over', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_game.Game')),
            ],
        ),
    ]
